title = "Metadata"
description = "Info about the wineglass version"

[compilerdata]
version = "0.0.1"
version_info = "First and initial version of Wineglass"

[winecellar]
version = "0.0.1"
version_info = "First and initial version of Wineglass"

[builddata]
version = "0.0.1"
version_info = "First build"